version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: biblioteca-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123*
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped